### ISSUE TITLE
Make arguments consistent with other tools

### ISSUE THREAD

**Issue by bharatvaj** [aaronamk/hkd#14]
You have used ',' to pass multiple devices but this will increases the work of the user.
The user won't be able to do, `hkd /dev/input/by-id/*` or other similar expansions if they want to.

Proposed solution:
Remove manual '-d' and  strtok ',' comma detection and get the args directly from argv and argc which are safer and less code and time.

Propsed usage: hkd [-vh] [device1] [devivce2]

**Comment by aaronamk** [comment]
Good point. I will try to tackle this this evening.
